package com.dz.itinfinity.backend_payment.domain.enums;

public enum EmailType {
    ONLINE_PAYMENT_SELLER,
    ONLINE_PAYMENT_BUYER_HOME_DELIVERY,
    ONLINE_PAYMENT_BUYER_DELIVERY_POINT,
    ONLINE_PAYMENT_BUYER_AT_SELLER,
    BANK_TRANSFER_PAYMENT_RESERVATION_FOR_SELLER,
    BANK_TRANSFER_PAYMENT_RESERVATION_FOR_BUYER,
    BANK_TRANSFER_PAYMENT_RESERVATION_CONFIRMED_BY_SELLER,
    BANK_TRANSFER_PAYMENT_RESERVATION_REFUSE,
    BANK_TRANSFER_PAYMENT_EXPIRED_DATE_BUYER,
    BANK_TRANSFER_PAYMENT_EXPIRED_DATE_SELLER,
    BANK_TRANSFER_PAYMENT_PAID_CONFIRM_BY_SELLER,
    BANK_TRANSFER_PAYMENT_PAID_CONFIRM_WAIT_BUYER,
    BANK_TRANSFER_PAYMENT_PAID_VALID_BUYER,
    BANK_TRANSFER_PAYMENT_PAID_VALID_SELLER,
    BANK_TRANSFER_PAYMENT_PAID_INVALID_BUYER,
    BANK_TRANSFER_INVALID_SELLER,
    BANK_TRANSFER_INVALID_BUYER
}
